// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace solar.Data.Tables
{
    public partial class alertasutilizador
    {
        public int Tipo { get; set; }
        public string Utilizador_username { get; set; }

        public virtual utilizador Utilizador_usernameNavigation { get; set; }
    }
}