// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace solar.Data.Tables
{
    public partial class alerta
    {
        public int idAlerta { get; set; }
        public DateTime dataHora { get; set; }
        public string descricao { get; set; }
        public string sugestoes { get; set; }
        public int TIPO { get; set; }
    }
}