// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace solar.Data.Tables
{
    public partial class avaria
    {
        public int Habitacao_idHabitacao { get; set; }
        public DateTime dataHora { get; set; }

        public virtual habitacao Habitacao_idHabitacaoNavigation { get; set; }
    }
}