// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace solar.Data.Tables
{
    public partial class evento
    {
        public evento()
        {
            lembrete = new HashSet<lembrete>();
        }

        public int idEvento { get; set; }
        public DateTime data { get; set; }
        public string descricao { get; set; }
        public DateTime dataFinal { get; set; }

        public virtual ICollection<lembrete> lembrete { get; set; }
    }
}