// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace solar.Data.Tables
{
    public partial class habitacao
    {
        public habitacao()
        {
            avaria = new HashSet<avaria>();
            consumoenergetico = new HashSet<consumoenergetico>();
            manutencao = new HashSet<manutencao>();
            painel = new HashSet<painel>();
        }

        public int idHabitacao { get; set; }
        public string morada { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public double bateria { get; set; }
        public double capacidade { get; set; }
        public int Localidade_idLocalidade { get; set; }
        public string Utilizador_username { get; set; }

        public virtual localidade Localidade_idLocalidadeNavigation { get; set; }
        public virtual utilizador Utilizador_usernameNavigation { get; set; }
        public virtual ICollection<avaria> avaria { get; set; }
        public virtual ICollection<consumoenergetico> consumoenergetico { get; set; }
        public virtual ICollection<manutencao> manutencao { get; set; }
        public virtual ICollection<painel> painel { get; set; }
    }
}