// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace solar.Data.Tables
{
    public partial class meteorologia
    {
        public DateTime data { get; set; }
        public int idLocalidade { get; set; }
        public string weatherType { get; set; }
        public string skyCondition { get; set; }
        public double probPrecipitacao { get; set; }
        public TimeSpan sunrise { get; set; }
        public TimeSpan sunset { get; set; }

        public virtual localidade idLocalidadeNavigation { get; set; }
    }
}