// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace solar.Data.Tables
{
    public partial class producaoenergetica
    {
        public DateTime data { get; set; }
        public double producao { get; set; }
        public int ID { get; set; }
        public int Painel_idPainel { get; set; }
        public int Painel_Habitacao_idHabitacao { get; set; }

        public virtual painel Painel_ { get; set; }
    }
}