// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace solar.Data.Tables
{
    public partial class utilizador
    {
        public utilizador()
        {
            alertasutilizador = new HashSet<alertasutilizador>();
            habitacao = new HashSet<habitacao>();
            lembrete = new HashSet<lembrete>();
        }

        public string username { get; set; }
        public string nome { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public DateTime lastTimeOnline { get; set; }

        public virtual funcionario funcionario { get; set; }
        public virtual ICollection<alertasutilizador> alertasutilizador { get; set; }
        public virtual ICollection<habitacao> habitacao { get; set; }
        public virtual ICollection<lembrete> lembrete { get; set; }
    }
}